### PR TITLE
Replace locking/unlocking of canvas with select/pan mode

### LINKED ISSUE #1011: [Feature Request]: Pan / Select mode switch with "Space" key
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

In design softwares like Photoshop, there are 2 modes to interact with the canvas:
- Pan mode: Lock the content, only changes view point of the canvas
- Select mode: No view point operation, user can only interact with the object on the canvas

Currently panning is achieved by dragging on empty space of the canvas, but this can be hard if the nodes / objects on the canvas are too congested.

### Proposed workflow

When "Space" is pressed and hold, enter Pan mode, otherwise enter select mode

### Additional information

Related issues: 
- https://github.com/Comfy-Org/ComfyUI_frontend/issues/593
- https://github.com/Comfy-Org/ComfyUI_frontend/issues/1007

### PR DESCRIPTION
**Pull request by huchenlei**
Closes https://github.com/Comfy-Org/ComfyUI_frontend/issues/1011

Press space now enters pan mode, i.e. the whole canvas is read-only, only view change. Locking icon replaced with pan icon.

https://github.com/user-attachments/assets/c7872532-a2ac-44c1-9e7d-9e03b5d1a80b

### CODE REVIEW

**Comment by JorgeR81** [comment]
I'm constantly planning to change settings.

Instead of a keybind to switch between modes, could we also have a shortcut like ALT or SHIFT + `click and drag` to pan ?

It may be some 3D software I used, but this seems more natural to me.

**Comment by huchenlei** [comment]
> I'm constantly planning to change settings.
> 
> Instead of a keybind to switch between modes, could we also have a shortcut like ALT or SHIFT + `click and drag` to pan ?
> 
> It may be some 3D software I used, but this seems more natural to me.

Custom keybinding config system is coming soon. There is just not a keybinding that suits everyone.

**Comment by JorgeR81** [comment]
Custom keybinds would be great !

Could this make a distinction between `press down` and `press up` ?

For instance, could it be possible to enter pan mode on `press down` and leave it on `press up`, instead of just clicking to switch between modes.

**Comment by JorgeR81** [comment]
> For instance, could it be possible to enter pan mode on press down and leave it on press up, instead of just clicking to switch between modes.

Oh, just tried ! That is the way it works now !

The visual feedback on the cursor is also great.

**Comment by ronan36880** [comment]
> > I'm constantly planning to change settings.
> > Instead of a keybind to switch between modes, could we also have a shortcut like ALT or SHIFT + `click and drag` to pan ?
> > It may be some 3D software I used, but this seems more natural to me.
> 
> Custom keybinding config system is coming soon. There is just not a keybinding that suits everyone.


Would the custom keybinding config system allow me to still immediately enter panning mode without pressing any mouse buttons? I'm guessing this PR is just one of many that will improve on this, but as it stands, v1.3.4 breaks a core feature that i'm used to. And as far as I'm aware, it's not really possible to workaround in my usecase, since I'm already holding the LMB when I press Space.

The following video was recorded on v1.3.3:

https://github.com/user-attachments/assets/34af2fe1-b052-43e3-9fc1-15d9c4d9452a

**Comment by JorgeR81** [comment]
> Would the custom keybinding config system allow me to still immediately enter panning mode without pressing any mouse buttons? I'm guessing this PR is just one of many that will improve on this, but as it stands, v1.3.4 breaks a core feature that i'm used to. And as far as I'm aware, it's not really possible to workaround in my usecase, since I'm already holding the LMB when I press Space.

Nice ! 

I didn't know about this. It could be very useful !

Normally I use `cg-use-everywhere` to make connections in large workflows, but we should have a solution without custom nodes, like this one.

**Comment by lldacing** [comment]
> > > I'm constantly planning to change settings.
> > > Instead of a keybind to switch between modes, could we also have a shortcut like ALT or SHIFT + `click and drag` to pan ?
> > > It may be some 3D software I used, but this seems more natural to me.
> > 
> > 
> > Custom keybinding config system is coming soon. There is just not a keybinding that suits everyone.
> 
> Would the custom keybinding config system allow me to still immediately enter panning mode without pressing any mouse buttons? I'm guessing this PR is just one of many that will improve on this, but as it stands, v1.3.4 breaks a core feature that i'm used to. And as far as I'm aware, it's not really possible to workaround in my usecase, since I'm already holding the LMB when I press Space.
> 
> The following video was recorded on v1.3.3:
> 
>  Chrome.2024-10-01.14-05-39.mp4

You can try https://github.com/niknah/quick-connections

**Comment by JorgeR81** [comment]
> You can try https://github.com/niknah/quick-connections

I've played around with the demo ( https://niknah.github.io/quick-connections/quick_conn.html?nodebug=1 )

It's a good idea. It would be nice have something like this in the core.

But it should have an option to only show the quick connections for nodes that are out of the screen. 

demo

**Pull request merged**
