### PR TITLE
[Electron] Migrate custom nodes

### PR DESCRIPTION
**Pull request by pythongosssss**
Adds custom node migration option and a generic toastr handler

┆Issue is synchronized with this [Notion page](https://www.notion.so/1892-Electron-Migrate-custom-nodes-15f6d73d365081c78633dab5c4b801d0) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by huchenlei** [comment]
Ref: electron side PR: https://github.com/Comfy-Org/desktop/pull/474

**Comment by robinjhuang** [comment]
Screenshot 2024-12-13 at 12 26 41 PM
@pythongosssss Should we add an additional selection box here?

**Comment by huchenlei** [comment]
> Screenshot 2024-12-13 at 12 26 41 PM @pythongosssss Should we add an additional selection box here?

It's driven by electron side. Please make sure you have the electron side change patched first.
Screenshot 2024-12-13 at 1 37 01 PM

**Review by huchenlei — CHANGES_REQUESTED** [review]
Can you split the global toast change to a separate PR? I feel like having 2 levels of toast now can be confusing. For the custom node migration error reporting, we can fall back to use a electron system level message alert for now, and land the migration part first.

**Review by huchenlei — APPROVED** [review]

**Pull request merged**
