### PR TITLE
feat: Adding download count badge to sidebar

### PR DESCRIPTION
**Pull request by oto-ciulis-tt**
https://github.com/user-attachments/assets/0c8d301a-15e3-4153-8044-708b1b2c8313

### CODE REVIEW

**Review by huchenlei — CHANGES_REQUESTED** [review]
This feature needs to be guarded behind `isElectron` flag.

**Comment by oto-ciulis-tt** [comment]
> This feature needs to be guarded behind `isElectron` flag.

Since ElectronDownloadStore doesn't populate downloads if it's not running in Electron context I think we don't need it since `downloads` will never be more than 0 so this badge won't show up. But I can add it for extra safety if you think it's needed.

**Comment by huchenlei** [comment]
> > This feature needs to be guarded behind `isElectron` flag.
> 
> Since ElectronDownloadStore doesn't populate downloads if it's not running in Electron context I think we don't need it since `downloads` will never be more than 0 so this badge won't show up. But I can add it for extra safety if you think it's needed.

`useElectronDownloadStore` cannot be called in non-electron context as is deconstruct the electronContext to get downloadManager here https://github.com/Comfy-Org/ComfyUI_frontend/blob/8af016ffc1e4a038afd100dbd9c3d4d579f656a7/src/stores/electronDownloadStore.ts#L16

I fixed this issue for your previous PR in https://github.com/Comfy-Org/ComfyUI_frontend/pull/1521. This is also why you see all playwright tests failing.

**Comment by oto-ciulis-tt** [comment]
> > > This feature needs to be guarded behind `isElectron` flag.
> > 
> > 
> > Since ElectronDownloadStore doesn't populate downloads if it's not running in Electron context I think we don't need it since `downloads` will never be more than 0 so this badge won't show up. But I can add it for extra safety if you think it's needed.
> 
> `useElectronDownloadStore` cannot be called in non-electron context as is deconstruct the electronContext to get downloadManager here
> 
> https://github.com/Comfy-Org/ComfyUI_frontend/blob/8af016ffc1e4a038afd100dbd9c3d4d579f656a7/src/stores/electronDownloadStore.ts#L16
> 
> I fixed this issue for your previous PR in #1521. This is also why you see all playwright tests failing.

Wouldn't it be more future-proof to update `useElectronDownloadStore` to take into account that `electronApi` can return `undefined` and update return type of `electronApi` to reflect that? I think it will be easy to forget to always wrap this with `isElectron()` test.

**Comment by huchenlei** [comment]
> > > > This feature needs to be guarded behind `isElectron` flag.
> > > 
> > > 
> > > Since ElectronDownloadStore doesn't populate downloads if it's not running in Electron context I think we don't need it since `downloads` will never be more than 0 so this badge won't show up. But I can add it for extra safety if you think it's needed.
> > 
> > 
> > `useElectronDownloadStore` cannot be called in non-electron context as is deconstruct the electronContext to get downloadManager here
> > https://github.com/Comfy-Org/ComfyUI_frontend/blob/8af016ffc1e4a038afd100dbd9c3d4d579f656a7/src/stores/electronDownloadStore.ts#L16
> > 
> > I fixed this issue for your previous PR in #1521. This is also why you see all playwright tests failing.
> 
> Wouldn't it be more future-proof to update `useElectronDownloadStore` to take into account that `electronApi` can return `undefined` and update return type of `electronApi` to reflect that? I think it will be easy to forget to always wrap this with `isElectron()` test.

I would say we actually want to let it fail if anything not in electron environment tries to call useElectronDownloadStore. At callsite src/hooks/sidebarTabs/modelLibrarySidebarTab.ts we do want future dev know that the badge is only displayed for electron environment, while now this silently depends on the fact that empty downloads just don't show up.

**Review by huchenlei — APPROVED** [review]

**Pull request merged**
