### PR TITLE
Add Markdown support to the Note node

### PR DESCRIPTION
**Pull request by gremlation**
This uses the (MIT licensed) [Tiptap](https://tiptap.dev) rich text editor to add Markdown support for the Note node. All the usual Markdown features are supported.

┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-2044-Add-Markdown-support-to-the-Note-node-1666d73d36508186991ad1b95a8f282d) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by huchenlei — CHANGES_REQUESTED** [review]
Please attach screenshots/video clips and explain how this widget should function, e.g. how does the feature switch between edit mode and view mode.

**Comment by gremlation** [comment]
Here's a screen recording. There's no separate edit/view modes, it works just the same as before, you just click in the text area and start typing.

https://github.com/user-attachments/assets/ac0c350a-ee5b-4dbf-9a7a-65ff9082880e

**Review by huchenlei — CHANGES_REQUESTED** [review]
Currently if we paste markdown text to the textarea, it is not detected as markdown. Can you fix it? Or I would suggest we have some sort of switching mechanism, i.e. double click textarea to enter edit mode where raw text is shown, and unfocus will show the rendered markdown.

**Comment by gremlation** [comment]
I've added an edit mode that switches to editing raw Markdown. You should be able to paste Markdown in there. I've also added link support.

https://github.com/user-attachments/assets/7fc6ba67-c6e3-41f1-9892-4506da7b27c8

**Review by huchenlei — APPROVED** [review]

**Comment by alessandroperilli** [comment]
Is it me or the markdown support doesn't support rendering tables? @gremlation

**Comment by gremlation** [comment]
Is this necessary @alessandroperilli? There's all sorts of things that could be added (code highlighting, task lists, YouTube embeds, etc.), but I was trying to strike a balance between the things people will actually use and throwing the kitchen sink in.

If this is something you think people will use, I've opened a pull request for table support in #2072

**Comment by alessandroperilli** [comment]
@gremlation personally, I use them inside APW. I'd be fine without markdown support for tables, but the problem is that without it, my "homemade tables in plain text" are screwed. So either we go for a modality switch, like MTB's Note+ node does, or I'd like support for them.

As a side node, I also have issues with headings. Somehow, I cannot place 2 headings of the same time in the same node. I have this issue with both # and ## headings.

**Comment by gremlation** [comment]
Okay, cool. The pull request is there then. I just tried the MTB Note+ node and it doesn't work for me at all. Not sure what the problem is.

When you say you have problems with the headings, do you mean with this Note node? It's working for me without a problem. Maybe it's a conflict with another extension? If you think it's a bug and can reproduce it without other extensions enabled, create an issue with debug info like browser version and tag me in it.

https://github.com/user-attachments/assets/f753b1ce-7e88-4767-b95b-47a58ff480f4

**Comment by yoland68** [comment]
FYI, this is creating backwards compatibility issues for all Notes that have single line breaks because of Markdown render:

https://github.com/user-attachments/assets/6324ea3f-9271-49bb-8abb-d657e9aa3db8

**Comment by yoland68** [comment]
Screenshot

**Comment by yoland68** [comment]
In my opinion, this should be a new node called "Markdown Note"

**Comment by yoland68** [comment]
Creating an issue here #2146

**Pull request merged**
