### PR TITLE
Fix image grid render consistency

### PR DESCRIPTION
**Pull request by webfiltered**
- Makes image grids of non-uniform-size images fill the space the same as uniform image batches
- Re-uses existing code
- Removes workaround
- "Supports image sizes up to 1 terapixel"
(at time of writing I hard-coded it to 1048576 x 1048576 max-size squares - how it behaved before, but that seemed silly)

#### Old

https://github.com/user-attachments/assets/9f405c57-a29b-4f44-9bd5-9d02b6b2a726

#### PR

https://github.com/user-attachments/assets/422b5774-06f0-4d66-ae1a-2f3b9d12cde3

#### Repro workflow

[ComfyUI_frontend-pull-654.json](https://github.com/user-attachments/files/16763920/ComfyUI_frontend-pull-654.json)

_Workflow requires: https://github.com/ltdrdata/ComfyUI-Impact-Pack/_

### CODE REVIEW

**Comment by huchenlei** [comment]
Can you attach a repro workflow?

**Comment by webfiltered** [comment]
Impact pack + segs model okay?

I don't know anything in ComfyUI core that outputs iterable images of disparate shapes - the nodes I just tried all output tensors, so they'd throw if they tried.

**Comment by huchenlei** [comment]
> Impact pack + segs model okay?
> 
> I don't know anything in ComfyUI core that outputs iterable images of disparate shapes - the nodes I just tried all output tensors, so they'd throw if they tried.

Can you share a JSON workflow file here? It can help future viewer of this PR easily reproduce and verify.

**Comment by webfiltered** [comment]
Sorry I meant - is it okay if the workflow uses node packs, and not just ComfyUI core?  I'll just drop one in anyway.

**Comment by huchenlei** [comment]
> Sorry I meant - is it okay if the workflow uses node packs, and not just ComfyUI core? I'll just drop one in anyway.

It's ok if the workflow needs custom nodes.

**Comment by webfiltered** [comment]
Excellent.  Also, as it probably didn't notify you - I edited it into the PR.

**Review by huchenlei — APPROVED** [review]
LGTM!

**Pull request merged**
