### PR TITLE
fix 'unsaved' value when closing workflows

### PR DESCRIPTION
**Pull request by mcmonkey4eva**
for #735

Linked issue describes the problem well. I replicated it locally, tested, found it comes down to just this variable not getting unset where other variables are unset at, so I unset it there. After this update, reopening a saved workflow that you opened previously does correctly treat the workflow as initially being not unsaved.

### CODE REVIEW

**Review by huchenlei — CHANGES_REQUESTED** [review]
Can you add a playwright test to verify the fix works?

**Comment by JorgeR81** [comment]
I also noticed workflows are set as unsaved, when we drag a PNG or JSON file.

Does this PR address this ?

( I was about to open an issue )

Most of the time, my "unsaved workflows" are just a PNG or JSON file I dragged in, to check the workflow.

This way, I can have 10 unsaved workflows or more. 
And sometimes I just want to clear all the clutter ( especially using workflow tabs ) but now need to confirm every time I close an workflow.

**Comment by mcmonkey4eva** [comment]
Well that genuinely is an unsaved workflow -- quicker ways to clear out random workflows (eg shift+click close to bypass unsaved prompt) would be a valid feature request to file

**Comment by mcmonkey4eva** [comment]
image
oh okay then :(

Relevant other tests around workflow management are skipped atm due to the workflow UI changearound breaking the test code

**Comment by mcmonkey4eva** [comment]
I don't really know what to do here other than mark the untested new test as skip pending the relevant 1.3 core test failures being fixed first

**Comment by mcmonkey4eva** [comment]
actually considering that's becoming a merge conflict issue and it's entirely untested anyway, I'm going to remove it for now, and recommend (cc @huchenlei ) that we merge as-is with just the fix and add a test later once the tests in general are able to properly test this section of code.

(Noting that this PR is a literal 1-line change minor bugfix and it has been sat waiting for 2 weeks and encountering merge conflicts due to the testing issues)

**Pull request closed without merging**
