### PR TITLE
Add tests on litegraph widget text truncate

### PR DESCRIPTION
**Pull request by christian-byrne**
Add tests for [Comfy-Org/litegraph.js#17](https://github.com/Comfy-Org/litegraph.js/pull/17)

### CODE REVIEW

**Review by huchenlei — APPROVED** [review]
LGTM! Thanks for your hard work!

**Comment by huchenlei** [comment]
BTW, we have a github action to automatically update linux-based screenshots, so you don't need to do the freshcheckout and have the default model selected to set expectation. To trigger that you just need to add label `New Browser Test Expectations`.

**Comment by huchenlei** [comment]
Small rendering diff. Setting expectation with Github action
image

**Comment by christian-byrne** [comment]
> BTW, we have a github action to automatically update linux-based screenshots, so you don't need to do the freshcheckout and have the default model selected to set expectation. To trigger that you just need to add label `New Browser Test Expectations`.

Oh that's good. Should I remove the screenshots from the PR and re -run to set them?

**Comment by christian-byrne** [comment]
> Small rendering diff. Setting expectation with Github action image

Is one of those using Roboto Mono and the other not?

**Comment by huchenlei** [comment]
> > Small rendering diff. Setting expectation with Github action image
> 
> Is one of those using Roboto Mono and the other not?

Not sure. I find this font issue only solvable if github action set the expectation by itself. 🤣

**Comment by christian-byrne** [comment]
> > > Small rendering diff. Setting expectation with Github action image
> > 
> > 
> > Is one of those using Roboto Mono and the other not?
> 
> Not sure. I find this font issue only solvable if github action set the expectation by itself. 🤣

Lol, I understand how it's supposed to go now

**Comment by huchenlei** [comment]
Hmmm, it might lack the permission to checkout your branch?

**Comment by christian-byrne** [comment]
> Hmmm, it might lack the permission to checkout your branch?

Not sure. Seems to work now though

**Comment by huchenlei** [comment]
Let me get it merged first and I am going to make another PR to update the test expectation with GA. I am going to merge it to the next release, v1.2 branch to avoid myself some trouble of merging back from main.

**Comment by Steudio** [comment]
Shouldn't the widget name be truncated instead of the widget value?
From a user perspective, the widget value is the most important and it is currently impossible to see the widget value without resizing.
It should look like the image on the right:
widget

**Comment by christian-byrne** [comment]
> Shouldn't the widget name be truncated instead of the widget value? From a user perspective, the widget value is the most important and it is currently impossible to see the widget value without resizing. It should look like the image on the right: widget

Generally I agree with you.

When I tried that, there were situations in which the input value was very long (checkpoints, file paths, text strings), and then the parameter name was essentially always hidden. The only way to see the parameter name in those situations was to expand the node extremely wide (sometimes off screen). Conversely, to see the full input value you can just click the widget.

**Comment by Steudio** [comment]
I understand your point and I would still argue that having a direct visual access to the widget value is more important than the widget name (when choosing to have the smallest node footprint).
1. Some long input value will never be compatible with small footprint workflow, so be it.
2. I feel that some widget values are self-explanatory and the widget name become less important (at least to advanced user?).
3. A mouse over popup showing the covered name should be enough to provide the hidden name (I did notice that some nodes already have a description of the widget, which is great)

mouse over example:
image

Regarding clicking the widget to show the whole value name, will it be possible to always show what the current value is?
I notice that some widget does show the currently selected value, but some do not.
image

**Comment by christian-byrne** [comment]
To me, all your points seem valid. I will have to try to get some other opinions.

**Pull request merged**
