### PR TITLE
Litegraph: Reroute support

### PR DESCRIPTION
**Pull request by webfiltered**
~~Worth adding a schema version, at this point.~~
Added.  New serialising interface is also being used:

Requires: https://github.com/Comfy-Org/litegraph.js/pull/279

Extends the workflow zod schema:
- Optional parentId on old LLink array format
- New LLink as an object
- Reroute object

### Notes
Only basic testing has been done - there's a lot of different uses of the serialised workflow, that this may break.

Naming (may still) need work - edits welcome!

### CODE REVIEW

**Comment by huchenlei** [comment]
We probably want to version the schema and write conversion function convert the old format to new format instead of directly adding a linksV2 field.

**Comment by huchenlei** [comment]
BTW, if I am understanding it correctly, we are going to support reroute natively in litegraph?

**Comment by webfiltered** [comment]
Yup!  Much simpler with these, as they are just visual points.  There will just be one LLink - from output to input.

**Review by huchenlei — COMMENTED** [review]
You can reference how InvokeAI setup the schema versioning here: https://github.com/invoke-ai/InvokeAI/blob/3b96c794618968df2981d0b2ea995afba690d527/invokeai/frontend/web/src/features/nodes/util/workflow/migrations.ts#L35

**Comment by webfiltered** [comment]
> You can reference how InvokeAI setup the schema versioning here: https://github.com/invoke-ai/InvokeAI/blob/3b96c794618968df2981d0b2ea995afba690d527/invokeai/frontend/web/src/features/nodes/util/workflow/migrations.ts#L35

I added some changes, but not sure if it's what you're after.

Do you want schema upgrade to happen on the ComfyUI side, with Litegraph oblivious?  I couldn't find anywhere in frontend that's doing more than just reading/writing the schema and passing it to Litegraph.

Currently it is set up as a non-breaking change for extensions:
- Frontend can read any version
- Litegraph can read any version
- The format you write is determined by the call you make to Litegraph

Also, thought about semantic versioning, but schemas rarely ever have more than a handful of versions (and with strict validation all changes are breaking), so I went with simple.

**Comment by webfiltered** [comment]
Force pushed:
- Rebased
- Squashed meandering commits
- Restored PR to original intent: add read-only support for Litegraph schema v1 workflows
- No other changes to existing behaviour

Edit: oh, and fixed a test (it was working, but not accurate).

**Review by huchenlei — APPROVED** [review]

**Pull request merged**
