### PR TITLE
Fix group node naming compatibility

### PR DESCRIPTION
**Pull request by christian-byrne**
#950 changed group node names' prefix from `workflow/` to `workflow>`. To be compatible with older workflows, change `workflow/` to `workflow>` in graph data when configuring.

Issue:

- https://github.com/comfyanonymous/ComfyUI/issues/5052

### CODE REVIEW

**Review by huchenlei — APPROVED** [review]

**Comment by mijuku233** [comment]
Strange, this PR seems to be to fix the bug that the group node in the workflow cannot be loaded?
But in fact, when using the 1.2.64 front end, no matter how the workflow is saved, the group node in it cannot be loaded by any version of the front end.

image

**Comment by christian-byrne** [comment]
> Strange, this PR seems to be to fix the bug that the group node in the workflow cannot be loaded? But in fact, when using the 1.2.64 front end, no matter how the workflow is saved, the group node in it cannot be loaded by any version of the front end.
> 

Thank you for reporting it.

Does it work when you disable ComfyUI-Manager? And can you share the workflow?

**Comment by mijuku233** [comment]
Workflows with group nodes can be saved normally when ComfyUI-Manager is disabled.
This is a simple test workflow (ComfyUI-Manager is not disabled).
[test.json](https://github.com/user-attachments/files/17135708/test.json)

**Comment by christian-byrne** [comment]
Just pushed a fix https://github.com/ltdrdata/ComfyUI-Manager/pull/1084

**Comment by mijuku233** [comment]
> Just pushed a fix [ltdrdata/ComfyUI-Manager#1084](https://github.com/ltdrdata/ComfyUI-Manager/pull/1084)

Thanks for fixing it, there is another bug about "manager and group node" https://github.com/ltdrdata/ComfyUI-Manager/issues/1080

**Pull request merged**
