### PR TITLE
Show keybinding on topbar dropdown menus

### PR DESCRIPTION
**Pull request by christian-byrne**
Select

- `TopMenuBar` use `id` of menu items to lookup keybindings 
- Menu items registered with `menuItemStore.ts#registerCommands` already inherit the command id 
- For `menuItemStore.ts#registerMenuGroup`, extend param type to include `id` field then add ids to the current menu items

### CODE REVIEW

**Comment by christian-byrne** [comment]
These tests fail when adding undo and redo to core keybindings:

```
  3 failed
    [chromium] › changeTracker.spec.ts:19:3 › Change Tracker › Can group multiple change actions into a single transaction 
    [chromium] › interaction.spec.ts:449:3 › Widget Interaction › Undo text input ──────────────────
    [chromium] › interaction.spec.ts:460:3 › Widget Interaction › Undo attention edit ──────────────
```

**Review by huchenlei — APPROVED** [review]

**Comment by huchenlei** [comment]
Overall the PR looks good. I did some refactorings on various things to make the vue side impl simpler.

**Comment by christian-byrne** [comment]
> Overall the PR looks good. I did some refactorings on various things to make the vue side impl simpler.

Wow that's much better, nice.

**Comment by amimi818** [comment]
Nice improvement! But could it be optimized a bit more to make it look better?   

image

**Comment by christian-byrne** [comment]
> Nice improvement! But could it be optimized a bit more to make it look better?
> 
>

Any suggestions in particular? The styling is taken directly from PrimeVue docs.

**Comment by christian-byrne** [comment]
I agree the line wrapping is not ideal. I would like to fix it but don't know which style is best:

keybinding-tags

**Comment by gremlation** [comment]
`white-space: nowrap` will stop the wrapping and the menu will expand horizontally to accommodate it.

image

**Comment by christian-byrne** [comment]
> `white-space: nowrap` will stop the wrapping and the menu will expand horizontally to accommodate it.
> 

Great point, we can also just change that. Which combination of styles would you say is best?

**Pull request merged**
